# 1. Database connection configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/numisma_db
spring.datasource.username=postgres
spring.datasource.password=c
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable Flyway
spring.flyway.enabled=false